export enum StatusEnum {
  PUBLISHED_BEFORE_APPROVAL = "PUBLISHED_BEFORE_APPROVAL",
  PUBLISHED_WITH_PROVIDER_SEGGESTION = "PUBLISHED_WITH_PROVIDER_SEGGESTION",
  ACTIVE_JESTA = "ACTIVE_JESTA",
  JESTA_FINISHED = "JESTA_FINISHED",
  CANCELED_JESTA = "CANCELED_JESTA"
};